# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  npm-intility-com:
    type: npm-registry
    url: https://npm.intility.com
    token: ${{ secrets.NPM_INTILITY_COM_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "ci:"

  - package-ecosystem: "github-actions"
    directory: "/react/.github/workflows"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "chore(react):"

  - package-ecosystem: "npm"
    directory: "/react"
    registries:
      - npm-intility-com
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "chore(react):"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      msal:
        patterns:
          - "@azure/msal-*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      patch-and-minor:
        patterns:
          - "*"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@azure/msal-*"
          - "@fortawesome/*"
        update-types:
          - patch
          - minor

  - package-ecosystem: "npm"
    directory: "/docusaurus"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "build(docs):"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "nuget"
    directory: "/dotnet/iwebapi/Company.WebApplication1"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      # considered fix because it affects the template itself, not the template package
      prefix: "fix(dotnet):"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "nuget"
    directory: "/dotnet/iworker/Company.Worker1"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      # considered fix because it affects the template itself, not the template package
      prefix: "fix(dotnet):"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
