name: build, test and publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    uses: intility/reusable-dotnet/.github/workflows/dotnet.yaml@v1.0.0
    with:
      docker: ${{ github.event_name != 'pull_request' }}
