apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ContainerRepositoryPlaceholder-dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/intility/ContainerRepositoryPlaceholder:main,
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/force-update: "true"
spec:
  project: __ARGO_PROJECT__
  destination:
    namespace: __OPENSHIFT_PROJECT_NAME__
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated: {}
  source:
    repoURL: https://github.com/intility/__REPOSITORY_NAME__.git
    targetRevision: HEAD
    path: k8s/overlays/dev
