apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ContainerRepositoryPlaceholder-dev

configMapGenerator:
  - name: ContainerRepositoryPlaceholder-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Development
