apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/high-availability

namespace: react-app-prod

labels:
  - pairs:
      app.kubernetes.io/part-of: react-app-prod
  - includeSelectors: true
    pairs:
      environment: prod

patches:
  - target:
      kind: Ingress
      name: react-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: react-app.intility.com
      - op: replace
        path: /metadata/labels/ingress-tenant
        value: default

# x-release-please-start-version
images:
  - name: ghcr.io/intility/<project-name>/react-app
    newTag: 0.0.0
# x-release-please-end
