apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ContainerRepositoryPlaceholder
  annotations:
    route.openshift.io/termination: edge
  labels:
    ingress-tenant: aa
spec:
  rules:
    - host: ContainerRepositoryPlaceholder.apps.int.intility.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ContainerRepositoryPlaceholder
                port:
                  number: 8080
